### ISSUE TITLE
Doesn't work when Go Project is outside the Go Folder

### ISSUE THREAD

**Issue by pixelprogrammer** [SublimeLinter/SublimeLinter-govet#16]
If Go project is outside the Go src folder using Go Modules, the `govet` linter doesn't print anything. The same code, when stored insde the `src` folder in your GOPATH, will work just fine.

The `go vet file.go` command works in the terminal just fine. It is able to print the errors just fine even though the Linter issues a similar shell command

`cmd = ("go", "vet", "${file_path}")`

I also have the `golint` Sublime Linter package as well and that one works just fine.

Go Version: 1.11.11 linux/amd64
System: Fedora

**Comment by cixtor** [comment]
Turning debug on in the SublimeLinter settings reveals that SublimeLinter-govet is calling the command like this `/usr/local/bin/go vet /path/to/the/project` so your test was wrong, because if you execute this command you will get the following error:

```
can't load package: package /path/to/the/project:
import "/path/to/the/project":
cannot import absolute path
```

The `go vet` doesn’t works when you call it using the relative path to the project. I am not sure if this is something to be fixed in `go vet` itself or if we need to modify the linter plugin to execute the command using the only supported syntax which is either `go vet ./...` or simply `go vet` _(assuming the linter is running in the correct path)_.

A temporary solution is to replace `${file_path}` with `${file}` so that the final command reads like `/usr/local/bin/go vet /path/to/the/file.go`. However, with this change SublimeLinter will only show warnings and errors in the current file rather than the whole project and we will end up with a report that many people will consider incomplete.

Another option is to replace `${file_path}` with `./...` so that the final command looks like `cmd = ('go', 'vet', './...')` and then override one of SublimeLinter’s functions to prevent the append of the project path to the end of the command. This change will have the same effect as executing the command in the Terminal which is what many people expect.

**Comment by pixelprogrammer** [comment]
I will give this a shot when I have a chance. Thanks for the response.

**Comment by pixelprogrammer** [comment]
This was printed in the console:

```
SublimeLinter: #8 linter.py:1155      govet: output:
  go: cannot find main module; see 'go help modules'
SublimeLinter: #8 linter.py:1195      govet: No matches for regex: (?P<file_path>^.+?):(?P<line>\d+):((?P<col>\d+):)?\s+(?P<message>(.|\n\t)+)
```
I tested the command again in terminal and you're right. Providing an absolute path to run the command or even using the command outside  gives a different result. Here is the output of both relative and absolute:

(GO111MODULE=on)

**inside the project folder**
```
go vet
# todoApp [todoApp.test]
./main.go:13:2: undefined: something

/usr/bin/go vet /path/to/project/server
# todoApp [todoApp.test]
./main.go:13:2: undefined: something
```

**outside the project folder**
```
$ go vet server
go: cannot find main module; see 'go help modules'

$ go vet server/main.go
go: cannot find main module; see 'go help modules'
```

(GO111MODULE=auto)
```
$ go vet server/
can't load package: package server: cannot find package "server" in any of:
	/usr/lib/golang/src/server (from $GOROOT)
	/home/joemoe/gocode/src/server (from $GOPATH)
```

Seems like the `go vet` command is just weird so nothing to do with this plugin per se. I updated the `go vet` source code to use `${file}` instead and it works for me. I am ok with it just being a single file for now.

Thanks

**Comment by kaste** [comment]
Should we make this customizable by the user? Something like 

```
defaults = {
	...
	'@target': '${file_path}'
}
```

*should* 🤞 do the trick if I'm not mistaken. Then a user could set this to `./...` or just `${file_on_disk}` or whatever.
